FROM elixir:1.6

ADD . /home/digital_signature.api
WORKDIR /home/digital_signature.api

RUN ln -s /home/digital_signature.api/priv/libUACryptoQ.so /usr/local/lib/libUACryptoQ.so.1
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV MIX_ENV=test

RUN mix do \
    local.hex --force, \
    local.rebar --force, \
    deps.get, \
    deps.compile
