FROM debian:stretch

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    gcc \
    make \
    git \
    wget \
    gnupg \
    locales \
    postgresql-9.6 \
    postgresql-client-9.6

USER postgres
RUN service postgresql start && psql -c "ALTER USER postgres PASSWORD 'postgres';"

USER root
# Set UTF-8 locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8

# Install Erlang & Elixir
RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && \
    DEBIAN_FRONTEND=noninteractive dpkg -i erlang-solutions_1.0_all.deb

RUN apt-get update && apt-get -y install \
    esl-erlang \
    elixir

ADD . /home/digital_signature.api
WORKDIR /home/digital_signature.api

ENV MIX_ENV=test

RUN mix do \
    local.hex --force, \
    local.rebar --force, \
    deps.get, \
    deps.compile
