FROM debian:latest

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    gcc \
    autoconf \
    ragel \
    make \
    git \
    wget \
    gnupg \
    locales \
    openssl \
    libssl-dev \
    postgresql-9.6 \
    postgresql-client-9.6

USER postgres
RUN service postgresql start && psql -c "ALTER USER postgres PASSWORD 'postgres';"

USER root
# Set UTF-8 locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8

# Install Erlang & Elixir
RUN wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && \
    DEBIAN_FRONTEND=noninteractive dpkg -i erlang-solutions_1.0_all.deb

RUN apt-get update && apt-get -y install \
    esl-erlang \
    elixir

RUN mkdir /home/DIGITAL_SIGNATURE.API
